services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["deno", "run", "--allow-all", "main.ts"]
